name: 编译安卓内核

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://android.googlesource.com/kernel/manifest
          kernel-branch: q-goldfish-android-goldfish-4.14-dev
          config: defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          python-2.7: true
          android-version: 10
          aosp-clang-version: r353983c
